### PR TITLE
Simple Delegation: no revert for `_canVoteFor` in `voteForMultiple`

### PR DESCRIPTION
**Pull request by katamarinaki**
### Changelog

- Use `if` instead of `revert` in `_canVoteFor` check inside `voteForMultiple`;
- revert `voteForMultiple` if the delegate hasn't managed to vote for anyone from the list.

### CODE REVIEW

**Review by bulbozaur — APPROVED** [review]

**Comment by skozin** [comment]
imo this flow would be ok when the lack of revert only happens iff, of all delegators that voting for has failed, it has failed due to the delegator voting himself but not some other reason (e.g. the delegator having no voting power). this solves the frontrunning issue but doesn't hide operational errors

**Comment by skozin** [comment]
ah, I see that the "no voting power" case already produces a revert

**Comment by skozin** [comment]
ok, so the impl in this PR fails quietly in three cases: 1) the delegator has voted themselves, 2) the delegator has revoked the voting power from the delegate, 3) the delegator wasn't delegating to the delegate at the start of the vote.

imo, the third case is the most problematic one and, while this PR improves the case of the delegator voting while some of the delegates have actively participated in the vote, it significantly degrades the case where the delegate inadvertently uses an incorrect delegate address and expects that the vote would include the complete delegated voting power (compared to the impl that loudly fails on any failed delegated vote).

the choice between the two impls is, imo, a product one and thus has to consider the context where this voting delegation system is expected to be used. as far as I understand, this is not a general delegation system (since it requires to explicitly pass all delegating addresses and entails linear gas cost increase per delegating address) and is intended to be used mostly with delegating addresses that are either known to or belong to the delegate.

in this context, the probability of a delegate revoking the voting power or voting on their own without the delegate expecting this is extremely low, while the probability of the delegate mistyping the address is still here. so degrading the visibility of an operational error for the sake of improving the very improbable front-running case is not worth it (and is not worth making the behavior more complex).

if this were a general delegation system, i'd fully support this impl. but if I'm correct with the usage context assumption, i don't think the impl is an optimal one (though i won't block it).

**Comment by bulbozaur** [comment]
> 3) the delegator wasn't delegating to the delegate at the start of the vote.

Note: it doesn't matter if delegator delegate his power before or after start of the vote

**Comment by skozin** [comment]
> Note: it doesn't matter if delegator delegate his power before or after start of the vote

yeah, from the technical perspective, i understand

i mean the case where the delegator wasn't delegating to the address that tries to votr for it, i.e. where a mistake is made by the delegate. imagine a fund manager voting from a "hot" address and mistyping the address of the custody address. in this case, the failure should be as loud as possible so they know that their vote wasn't counted

**Comment by skozin** [comment]
the mistype producing an address that has voting power but doesn't delegate it to the actor is almost impossible so it would still lead to a revert (that's why i won't block this impl) but, imo, in the intended usage context, the proposed change is not worth complicating the system behavior

**Comment by bulbozaur** [comment]
Maybe restriction that delegator can delegate to address with non zero LDO balance could help to deal with it

**Comment by bulbozaur** [comment]
> where a mistake is made by the delegate.

in  case of our UI 3rd party code it could be checked with dry call, so it is not so big issue imo, but off chain developer should keep in mind such case.

**Comment by katamarinaki** [comment]
Considering all the pros and cons of this approach, the DAO ops team has decided to move forward with this tweak. This way, we will eliminate the possibility of the front-run attack and improve UX: delegates won't have to re-do the voting action if someone unassigns them as a delegate or votes themself at the last moment. 

To reflect this change in code we also decided to rename delegates' voting methods: from `voteFor` to `attemptVoteFor`.

**Pull request merged**
